### ISSUE TITLE
Requests are not being logged to stdout of docker-compose

### ISSUE THREAD

**Issue by chipironcin** [bitnami/bitnami-docker-phabricator#46] opened 2017-01-23 19:03 UTC
Hi guys
I tried latest Bitnami Phabricator from Github with `docker-compose up`.
It seems Apache access_log is being logged to stout, but when I navigate Phabricator, requests do not appear. It seems like stuck with the first requests that were automatically made.

Is it mean to log Apache activity or to stay stale?

**Comment by juan131** [comment] 2017-01-27 10:30
The issue seems to be not related with this Docker Image. 
The problem seems to be specific to the Host environment that calls Docker.

We will leave this issue opened until we have more specific details.

**Comment by juan131** [comment] 2017-01-30 17:01
We confirmed that the problem is in the Host environment that calls Docker not in the Docker Image. We'll close this issue.

**Comment by chipironcin** [comment] 2017-01-30 17:13
The reporter is the one who has to confirm that.
I confirm it is due to the way the volume where I am writting the logs is mounted. That volume has been mounted with some options that indicate to not update the `accessedTime` or `atime` but only `modifiedTime` or `mtime` when updating a file.

That is causing Phabricator or Nami not updating the output with the contents of the log file.
But my volume is healthy and this container should work despite my mount options.

Could you make sure to open an issue in the tool that is handling the logs or point me to it?

**Comment by juan131** [comment] 2017-02-13 12:07
We opened an issue to fix it on Nami. https://github.com/bitnami/nami/issues/31

We take care of it and let you know when it is solved.

**Comment by sameersbn** [comment] 2017-04-27 07:28
issue seems to be fixed  with new releases of the image. closing, please re-open if you think otherwise.

**Closed by sameersbn** 2017-04-27 07:28 UTC
