### ISSUE TITLE
Error executing 'postInstallation': ELOOP: too many symbolic links encountered

### ISSUE THREAD

**Issue by fdcastel** [bitnami/bitnami-docker-phabricator#41] opened 2017-01-20 19:27 UTC
Trying to bring up a new installation with both `2017.02-r0` and `2016.53-r0` fails with

```
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system user...
phabric INFO  Creating Phabricator temporary folders...
phabric INFO  Configuring Apache settings...
phabric INFO  Configuring PHP settings...
phabric INFO  Checking connection to database...
mysqlCo INFO  Trying to connect to MySQL server
mysqlCo INFO  Found MySQL server listening at ************-mariadb:3306
mysqlCo INFO  MySQL server listening and working at ************-mariadb:3306
phabric INFO  Creating Database...
phabric INFO  Configuring Phabricator...
Error executing 'postInstallation': socket hang up
socket hang up
nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system user...
phabric INFO  Creating Phabricator temporary folders...
phabric INFO  Configuring Apache settings...
Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/phabricator/logs/.htaccess'
```

Using `2016.46-r4` it works fine:

```
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system user...
phabric INFO  Creating Phabricator temporary folders...
phabric INFO  Configuring Apache settings...
phabric INFO  Configuring PHP settings...
phabric INFO  Checking connection to database...
mysqlCo INFO  Trying to connect to MySQL server
mysqlCo INFO  Found MySQL server listening at ************-mariadb:3306
mysqlCo INFO  MySQL server listening and working at ************-mariadb:3306
phabric INFO  Creating Database...
phabric INFO  Configuring Phabricator...
phabric INFO
phabric INFO  ########################################################################
phabric INFO   Installation parameters for phabricator:
phabric INFO     Host: ************
phabric INFO     First Name: FirstName
phabric INFO     Last Name: LastName
phabric INFO     Username: user
phabric INFO     Password: **********
phabric INFO     Email: user@example.com
phabric INFO   (Passwords are not shown for security reasons)
phabric INFO  ########################################################################
phabric INFO
nami    INFO  phabricator successfully initialized
Starting application ...

  *** Welcome to the phabricator image ***
  *** Brought to you by Bitnami ***
  *** More information: https://github.com/bitnami/bitnami-docker-phabricator ***
  *** Issues: https://github.com/bitnami/bitnami-docker-phabricator/issues ***
```

Environment:

**uname -a**
```
Linux web3 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**docker version**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Comment by prydonius** [comment] 2017-01-20 20:01
Thanks @fdcastel, I couldn't reproduce it on Docker for Mac. @sameersbn @migmartri could you try on ubuntu?

**Comment by fdcastel** [comment] 2017-01-20 20:30
Some more info. I don't know if it is related:

After the successful initialization from `2016.46-r4` I updated the docker image to `2017.02-r0`. This time it started fine, but the main web page told me to upgrade the DB Schema. So, I did run (inside the container)

```
/opt/bitnami/phabricator/bin/storage upgrade --force
```

And the output:

```
Applying patch "phabricator:20161115.phamepost.01.subtitle.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161115.phamepost.02.header.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161121.cluster.01.hoststate.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161124.search.01.stopwords.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161125.search.01.stemmed.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161130.search.01.manual.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161130.search.02.rebuild.php" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161210.dashboards.01.author.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161210.dashboards.02.author.php" to host "***********-mariadb:3306"...
Building Dashboard authorPHIDs...
Done
Applying patch "phabricator:20161211.menu.01.itemkey.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161211.menu.02.itemprops.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161211.menu.03.order.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161212.dashboardpanel.01.author.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161212.dashboardpanel.02.author.php" to host "***********-mariadb:3306"...
Building Dashboard Panel authorPHIDs...
Done
Applying patch "phabricator:20161212.dashboards.01.icon.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161213.diff.01.hunks.php" to host "***********-mariadb:3306"...
Migrating old hunks...
Done.
Applying patch "phabricator:20161216.dashboard.ngram.01.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20161216.dashboard.ngram.02.php" to host "***********-mariadb:3306"...
Applying patch "phabricator:20170106.menu.01.customphd.sql" to host "***********-mariadb:3306"...
Applying patch "phabricator:20170109.diff.01.commit.sql" to host "***********-mariadb:3306"...
Storage is up to date. Use "storage status" for details.
Synchronizing static tables...
Verifying database schemata on "***********-mariadb:3306"...


Database                         Table                    Name       Issues
bitnami_phabricator_conpherence  conpherence_index                   Better Table Engine Available
bitnami_phabricator_dashboard    dashboard                name       Better Collation Available
bitnami_phabricator_dashboard    dashboard_panel          name       Better Collation Available
bitnami_phabricator_differential differential_changeset   oldFile    Better Collation Available, Better Character Set Available, Wrong Column Type
bitnami_phabricator_differential differential_changeset   filename   Better Collation Available, Better Character Set Available, Wrong Column Type
bitnami_phabricator_differential differential_diff        key_commit Missing Key
bitnami_phabricator_metamta      metamta_applicationemail            Better Table Engine Available
bitnami_phabricator_search       search_documentfield                Better Table Engine Available
bitnami_phabricator_search       search_documentfield     corpus     Surplus Key
bitnami_phabricator_search       search_documentfield     key_corpus Missing Key
Applying schema adjustments...
sh: 1: tput: not found
sh: 1: tput: not found
[                                                                  ]   0.0%sh: 1: tput: not found
sh: 1: tput: not found
[=========================                                         ]  38.0%sh: 1: tput: not found
sh: 1: tput: not found
[=============================                                     ]  44.0%sh: 1: tput: not found
sh: 1: tput: not found
[===================================-                              ]  54.0%sh: 1: tput: not found
sh: 1: tput: not found
[====================================~                             ]  56.0%sh: 1: tput: not found
sh: 1: tput: not found
[====================================================~             ]  80.0%sh: 1: tput: not found
Done.
Completed applying all schema adjustments.
sh: 1: tput: not found
```

It appears to be working fine. But I don't know if that `sh: 1: tput: not found` could be a problem.

**Comment by fdcastel** [comment] 2017-01-20 20:47
Also, it keeps me warning from wrong `php.ini` settings, but they are actually right:

```
cat /bitnami/php/conf/php.ini | grep always_populate
always_populate_raw_post_data = -1
```

![image](https://cloud.githubusercontent.com/assets/629408/22164640/4119ef90-df3f-11e6-8b54-2ec6222f3b2c.png)

That "(none)" is bugging me. Someone knows from WHERE phabricator get this setting?

I thought maybe I was changing the wrong `.ini` file  file but there is only one `php.ini` in the entire container filesystem:

```
cd /
find | grep php.ini

./bitnami/php/conf/php.ini-development
./bitnami/php/conf/php.ini-production
./bitnami/php/conf/php.ini
./opt/bitnami/php/include/php/main/php_ini.h

```

I also tried to change `php.ini-production`, but the warning remains.

**Comment by migmartri** [comment] 2017-01-20 22:02
Hi

I ran the latest version (`2017.02-r0`) successfully.

I am using Ubuntu but we have mismatch kernel versions in the host as well as the version of docker.

```bash
Linux migmartri-XPS-13-9350 4.8.0-34-generic 
```

```bash
docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

@fdcastel how are you bringing up the environment, are you using docker-compose? Are you using the default compose file provided in the repository or a modified one?

Thanks,
Miguel

**Comment by fdcastel** [comment] 2017-01-20 22:29
Thanks for the test and for the info, @migmartri and @prydonius. I'm a bit behind of your setups:

I'm using docker-compose with the same settings from this repository README.md, except I'm using it in docker-compose v1 format:

```
phabricator:
  container_name: container-phabricator
  image: bitnami/phabricator:2017.02-r0
  restart: always
  links:
    - mariadb:mysql
  environment:
    - PHABRICATOR_HOST=container
    - MARIADB_HOST=container-mariadb
    - MARIADB_PASSWORD=********
  expose:
    - 80
  volumes:
    - ./preamble.php:/opt/bitnami/phabricator/support/preamble.php
    - container-phabricator-data:/bitnami/phabricator
    - container-apache-data:/bitnami/apache
    - container-php-data:/bitnami/php
mariadb:
  container_name: container-mariadb
  image: bitnami/mariadb:latest
  restart: always
  environment:
    - MARIADB_ROOT_PASSWORD=********
  volumes:
    - container-mariadb-data:/bitnami/mariadb
```

The need for v1 format is due to other containers I'm using (nginx-proxy, docker-letsencrypt-nginx-proxy-companion). I'm using this setup with success since 2016.31.

Just for the sake of information: I first tried the above setup with `2017.02-r0` and it crashed. Then I deleted all containers and volumes and tried again with `2016.53-r0`, but it also crashed. Again, I did clean everything and tried with `2016.46-r4` and it worked. 

So, whatever is causing this, it is surely something between `2016.46-r4` and `2016.53-r0`.

While I'm sad I can't offer a better reproducible case, it is good to know it is working with the latest setups.

So, if you could, please try it once more with a docker-compose script in v1 format like mine above. If you can't reproduce the problem, let's close this one for now.

**Comment by prydonius** [comment] 2017-01-21 01:31
@fdcastel thank you so much for filing these issues and for the information, I was able to reproduce the issue with your docker-compose file on Docker for Mac.

We'll investigate what changed in our package from `2016.46-r4` to `2016.53-r0` and figure out what could be causing this.

**Comment by migmartri** [comment] 2017-01-21 01:42
I can reproduce the same issue in my Ubuntu machine.

Apart of the reported error, I can see other errors coming up in the subsequent runs.

```
container-phabricator | Error executing 'postInstallation': Server returned status code 500 from http://127.0.0.1/auth/register
container-phabricator | Server returned status code 500 from http://127.0.0.1/auth/register
container-phabricator exited with code 1
```
```
container-phabricator | Error executing 'postInstallation': Unable to start com.bitnami.apache: AH00112: Warning: DocumentRoot [/tmp/1484962592482.8596] does not exist
container-phabricator | : AH00112: Warning: DocumentRoot [/tmp/1484962592482.8596] does not exist
container-phabricator | 
container-phabricator exited with code 1
```
```
container-phabricator | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/phabricator/logs/.htaccess'
container-phabricator | Error executing 'postInstallation': Unable to start com.bitnami.apache: AH00112: Warning: DocumentRoot [/tmp/1484962592482.8596] does not exist
```

**Comment by chipironcin** [comment] 2017-01-23 18:10
In the commit 2ce258b9432d7ed3a77ea433390dc4124c6f1a7a we also updated the dependencies so it is probably an issue in the PHP module. @juan131 can you take a look?

**Comment by juan131** [comment] 2017-01-27 11:57
The error:
```
Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/phabricator/logs/.htaccess'
```
Appears because of the `restart: always` you add to the docker-compose.yml file. There's a problem the first time it tries to initialise Phabricator. When it tries to initialise Phabricator the second time because of the "retry", it finds some problems in the htaccess file.
The issue is on the first initialisation as @migmartri pointed:
```
container-phabricator | Error executing 'postInstallation': Server returned status code 500 from http://127.0.0.1/auth/register
container-phabricator | Server returned status code 500 from http://127.0.0.1/auth/register
container-phabricator exited with code 1
```
Taking a look to the Apache logs, the error is related with the file preamble.php you added (in my case it's complaining about an empty file since I did not create it, I guess that the content of that file is conflictive in your case):
```
[Fri Jan 27 11:54:06.547349 2017] [:error] [pid 102] [client 127.0.0.1:37500] PHP Warning:  require_once(/opt/bitnami/phabricator/support/preamble.php): failed to open stream: No such file or directory in /opt/bitnami/phabricator/webroot/index.php on line 46
[Fri Jan 27 11:54:06.547401 2017] [:error] [pid 102] [client 127.0.0.1:37500] PHP Fatal error:  require_once(): Failed opening required '/opt/bitnami/phabricator/support/preamble.php' (include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/phabricator/webroot/index.php on line 46
```

**Comment by fdcastel** [comment] 2017-01-31 20:47
Thanks @juan131 for your explanations. 

In general I use `restart: always` in all my docker deployments. Should I remove it? There's some kind of "monitor" service in bitnami-docker-phabricator image which would restart the service if it crashes?

Also, I don't know if I understand the root cause of this error. The file `preamble.php` always existed in all my attempts (I need it because I use nginx as a reverse-proxy for phabricator -- more info [here](https://secure.phabricator.com/book/phabricator/article/configuring_preamble/)). 

Did you find why it failed only after `2016.53-r0` versions but not in `2016.46-r4` ?

Do you know if I upgrade to `2017.04-r0` this would occur again?

**Comment by fdcastel** [comment] 2017-01-31 23:29
Sorry, I upgraded to `2017.04-r0` but now I remember I already had upgraded my installation to `2017.02-r0` two weeks ago.

The problem only occurs when doing a clean (first) install. Not during upgrades.

Please close this one as you deem appropriate. 👍

**Comment by juan131** [comment] 2017-02-13 11:49
@fdcastel we proceed to close the issue. 

Regarding using `restart: always` I wouldn't recommend you to use it since it will restart the whole container instead of the service. It could generate lots of inconsistence issues as the one you find before. 

We don't have any monitor service in the Image. You can obtain the status of the server running `nami status SERVICE` (`nami status phabricator` in your case).

**Closed by juan131** 2017-02-13 11:49 UTC
