### ISSUE TITLE
Updating from bitnami/phabricator:2018.15.0-r0

### ISSUE THREAD

**Issue by pdhimal1** [bitnami/bitnami-docker-phabricator#116] opened 2019-02-25 15:31 UTC
Everything was running fine on `bitnami/phabricator:2018.15.0-r0`

We are looking to update to the new version but ran into Outgoing mail problems.

I followed the instructions here: https://github.com/bitnami/bitnami-docker-phabricator#smtp-configuration

I followed the instructions here: https://docs.bitnami.com/virtual-machine/apps/phabricator/configuration/configure-smtp/

Nothing seems to be working.

Looks like our old `phpmailer` settings are still there. 

Any help would be appreciated.

**Comment by marcosbc** [comment] 2019-02-26 16:33
Hi @pdhimal1, in Phabricator 2019.8 I could get SMTP to work properly. You need to follow the steps shown at https://github.com/bitnami/bitnami-docker-phabricator#smtp-configuration, by adding proper environment variables.

There are some things you might keep in mind, see: https://docs.bitnami.com/virtual-machine/how-to/troubleshoot-smtp-issues/

**Comment by pdhimal1** [comment] 2019-02-26 17:18
Hi @marcosbc thank you for getting back to me. I could get probably get this working on a clean install, but what if I had to run phabricator with 100s of GB of persisted data?

**Comment by marcosbc** [comment] 2019-02-28 14:33
Hi @pdhimal1, we have been able to get it working, find our instructions below:

First, create the SMTP configuration and insert it as below:

```
$ cat > smtp-config.txt <<EOF
[
  {
    "key": "stmp-mailer",
    "type": "smtp",
    "options": {
      "host": "smtp.gmail.com",
      "port": 587,
      "user": "EMAIL@DOMAIN",
      "password": "PASSWORD",
      "protocol": "tls"
    }
  }
]
```

Then execute the command below, again inside the Phabricator container:

    $ /opt/bitnami/phabricator/bin/config set cluster.mailers --stdin < smtp-config.txt

Finally restart the Docker container running Phabricator:

    $ docker-compose restart phabricator

It seems the issue is because the instructions are outdated, and it is not possible to set Phabricator configuration like is currently described in the docs. We'll work on updating it.

Hope it works!

**Comment by pdhimal1** [comment] 2019-02-28 16:18
@marcosbc Thanks for the update. Updating the documentations sounds like a good idea. I also didn't see documentation on notification servers. I have those running on my end, would be happy to contribute.

**Comment by marcosbc** [comment] 2019-03-01 08:32
Hi @pdhimal1, if adding them is simple feel free to send the PR to update the readme.

If not you could describe the step-by-step instructions here and we will adapt them for docs.bitnami.com.

Thanks!

**Comment by pdhimal1** [comment] 2019-03-07 19:49
@marcosbc here you go:

You'll need to forward port 22280, if you are using a docker-compose file:
 - `'22280:22280'`

Run the following commands on the `<your-phab-container>` to install `nodejs` and other dependencies:
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get -y install nodejs
cd /opt/bitnami/phabricator 
npm install ws
```

You can also do this on a Dockerfile:
```
FROM bitnami/phabricator:<tag>
RUN apt-get update
RUN apt-get -y install npm
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN sudo apt-get -y install nodejs
RUN cd /opt/bitnami/phabricator && npm install ws
```

Run the notification server (on the container) using the following command (Can't run it as the root user):
`su phabricator -c './bin/aphlict start'`

If the servers are already started, use the following command:
`su phabricator -c './bin/aphlict restart'`

Navigate to  `<your-phabricator-url>/config/edit/notification.servers/` and change the notification servers to:
```
[
  {
    "type": "client",
    "host": "your-phabricator-url",
    "port": 22280,
    "protocol": "http"
  },
  {
    "type": "admin",
    "host": "127.0.0.1",
    "port": 22281,
    "protocol": "http"
  }
]
```
Finally, navigate to `<your-phabricator-url>/config/cluster/notifications/` and verify that the notification servers are connected.
[
Notifications User Guide: Setup and Configuration](https://secure.phabricator.com/book/phabricator/article/notifications/)

**Comment by marcosbc** [comment] 2019-03-08 14:42
That's awesome @pdhimal1, thank you for sharing! I've created an internal task for documenting or enabling this feature in containers.

Unfortunately it can take some time if we decide to implement it, but it's a lot simpler now that it is exactly clear what needs to be done.

As for this issue, since it seems to be resolved, I'll proceed to close it.

**Closed by marcosbc** 2019-03-08 14:42 UTC
