### ISSUE TITLE
arc land induces bad state: fatal: could not set 'remote.origin.url' 

### ISSUE THREAD

**Issue by clockworksoul** [bitnami/bitnami-docker-phabricator#68] opened 2017-04-11 18:35 UTC
Hi,

We're running the image version `2017.13-r0`. 

We're finding that whenever we land a revision, the Phabricator repository ends up in a bad state. Specifically, updates stop working, and an error is reported on the `/diffusion/FOO/manage/status/` page as follows:

```
RAW ERROR
Error updating working copy: Command failed with error #128!
COMMAND
git remote set-url origin -- '********'

STDOUT
(empty)

STDERR
error: could not lock config file config: Permission denied
fatal: could not set 'remote.origin.url' to 'git@github.com:SeamlessDocsDev/foo.git'
```

This status can be temporarily (until the next land) corrected using the `bin/repository update --trace FOO` command.

This may or may not be related to https://github.com/bitnami/bitnami-docker-phabricator/issues/49

- Output of `docker version`:

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: ip-10-0-37-190
ID: XZYD:CF7O:JP2C:JOC2:DM7T:PCSX:66VY:IILR:5VF5:JDFC:AJJ6:F35X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running on an AWS instance with an Ubuntu Server 16.04 LTS AMI.

**Comment by chipironcin** [comment] 2017-04-13 11:10
Hi @clockworksoul 
Thanks for filing an issue. It seems related to permissions.
Our team will look at it shortly.

**Comment by javsalgar** [comment] 2017-04-13 15:28
Hi, 

I tried to reproduce the issue by doing the following:

  - I created a new repository
  - I added an observe URI to my own github repo
  - It was imported successfully
  - I created a diff
  - I landed it 
  - I went to Phabricator and clicked on Update the repository

Everything worked without issues. Could you let us know how you configured your repository in Phabricator? Did you use a observe URI or a mirror URI? Do the files in `/bitnami/phabricator` belong to the user `phabricator` (the one we use for managing the repositories)?

**Comment by sameersbn** [comment] 2017-04-27 06:54
Hello @clockworksoul, did you get a chance to look at the last comment?

**Comment by clockworksoul** [comment] 2017-04-27 17:07
Hi! 

I created the repos using the process described in https://github.com/bitnami/bitnami-docker-phabricator#restoring-a-backup, and the files all belonged to `root`.  

I'm `chown`-ing them to `phabricator:phabricator`; I'll let you know if that took care of the issue.

**Comment by clockworksoul** [comment] 2017-04-27 17:30
This did not resolve the issue, the same error state returns on land.

Furthermore, the following issue has appeared in the "unresolved setup issues" list:
`Local Disk Storage Not Readable/Writable
Configured location for storing uploaded files on disk ("/opt/bitnami/phabricator/data") does not exist, or is not readable or writable. Verify the directory exists and is readable and writable by the webserver.`

**Comment by javsalgar** [comment] 2017-05-08 09:19
It looks like you changed the permissions in more folders apart from the `repo` one. This is the default setting in a bitnami-phabricator container:

```
root@dc75a5bf64c0:/bitnami/phabricator# ls -l
total 12
drwxr-xr-x 5 root        root        4096 May  8 09:09 conf
drwxr-xr-x 3 daemon      daemon      4096 May  8 09:09 data
drwxr-xr-x 2 phabricator phabricator 4096 May  8 09:09 repo
```
Could you double-check that these are the permissions you set?

**Closed** 2017-08-22 17:45 UTC
Labels: bug
