### ISSUE TITLE
docker-compose up -d is not working

### ISSUE THREAD

**Issue by pahaz** [bitnami/bitnami-docker-phabricator#88] opened 2017-12-14 23:12 UTC
**Description**

I just run commands:
```
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-phabricator/master/docker-compose.yml > docker-compose.yml
dokcer-compose up -d
```

**Describe the results you received:**

Site Not Found
This request asked for "/" on host "178.62.222.122", but no site is configured which can serve this request.

`docker logs -f xxx_phabricator_1`:
```

Welcome to the Bitnami phabricator container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
phabric INFO  Configuring Apache settings...
phabric INFO  Configuring PHP settings...
phabric INFO  Checking connection to database...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
phabric INFO  Creating Database...
phabric INFO  Configuring Phabricator...
phabric INFO
phabric INFO  ########################################################################
phabric INFO   Installation parameters for phabricator:
phabric INFO     Host: 127.0.0.1
phabric INFO     First Name: FirstName
phabric INFO     Last Name: LastName
phabric INFO     Username: user
phabric INFO     Password: **********
phabric INFO     Email: user@example.com
phabric INFO   (Passwords are not shown for security reasons)
phabric INFO  ########################################################################
phabric INFO
nami    INFO  phabricator successfully initialized
INFO  ==> Starting phabricator...
127.0.0.1 - - [14/Dec/2017:23:06:27 +0000] "GET /res/defaultX/phabricator/4c79d74f/core.pkg.js HTTP/1.1" 200 196473
127.0.0.1 - - [14/Dec/2017:23:06:27 +0000] "GET /res/defaultX/phabricator/3010e992/rsrc/externals/javelin/core/init.js HTTP/1.1" 200 3110
127.0.0.1 - - [14/Dec/2017:23:06:27 +0000] "GET /logout HTTP/1.1" 302 -
127.0.0.1 - - [14/Dec/2017:23:06:27 +0000] "GET /logout/ HTTP/1.1" 200 19808
127.0.0.1 - - [14/Dec/2017:23:06:27 +0000] "GET /res/defaultX/phabricator/4c79d74f/core.pkg.js HTTP/1.1" 200 196473
127.0.0.1 - - [14/Dec/2017:23:06:27 +0000] "GET /res/defaultX/phabricator/3010e992/rsrc/externals/javelin/core/init.js HTTP/1.1" 200 3110
127.0.0.1 - - [14/Dec/2017:23:06:27 +0000] "POST /logout/ HTTP/1.1" 302 -
127.0.0.1 - - [14/Dec/2017:23:06:28 +0000] "GET /auth/loggedout/ HTTP/1.1" 200 5419
127.0.0.1 - - [14/Dec/2017:23:06:28 +0000] "GET /res/defaultX/phabricator/3010e992/rsrc/externals/javelin/core/init.js HTTP/1.1" 200 3110
127.0.0.1 - - [14/Dec/2017:23:06:28 +0000] "GET /res/defaultX/phabricator/4c79d74f/core.pkg.js HTTP/1.1" 200 196473
phabric INFO  Checking database connection before trying to start Phabricator daemons...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
[14-Dec-2017 23:06:32 UTC] 2017-12-14 11:06:32 PM [OVER] Started new daemon overseer (with PID "249").
127.0.0.1 - alincoln [14/Dec/2017:23:06:39 +0000] "GET /test-%252A/?duck-sound=quack HTTP/1.1" 200 177
46.148.199.86 - - [14/Dec/2017:23:06:38 +0000] "GET / HTTP/1.1" 500 731
127.0.0.1 - alincoln [14/Dec/2017:23:06:55 +0000] "GET /test-%252A/?duck-sound=quack HTTP/1.1" 200 177
46.148.199.86 - - [14/Dec/2017:23:06:55 +0000] "GET / HTTP/1.1" 500 731
127.0.0.1 - alincoln [14/Dec/2017:23:07:05 +0000] "GET /test-%252A/?duck-sound=quack HTTP/1.1" 200 177
46.148.199.86 - - [14/Dec/2017:23:07:05 +0000] "GET / HTTP/1.1" 500 731
127.0.0.1 - alincoln [14/Dec/2017:23:07:07 +0000] "GET /test-%252A/?duck-sound=quack HTTP/1.1" 200 177
46.148.199.86 - - [14/Dec/2017:23:07:07 +0000] "GET /favicon.ico HTTP/1.1" 500 738
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 13
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 71
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: maya-redmine
ID: HNEZ:3CBL:QN4Q:YUMV:IGWU:NSPL:3I2G:L6PR:PYBG:YMIM:YG52:YABA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

digitalocean.com

**Comment by javsalgar** [comment] 2017-12-15 10:50
Hi,

If you are using an external IP then you need to set the environment variable     `PHABRICATOR_HOST`.

More info: https://github.com/bitnami/bitnami-docker-phabricator#environment-variables

Best regards,

Javier J. Salmerón

**Comment by pahaz** [comment] 2017-12-15 14:23
Thanks. 

I change the variable and there is no result:

```
$ docker exec -it xxx_phabricator_1 bash
$ env
...
PHABRICATOR_HOST=178.62.222.122
...
```

And after that I have the same results:
```
Site Not Found
This request asked for "/" on host "178.62.222.122", but no site is configured which can serve this request.

```

**Comment by javsalgar** [comment] 2017-12-19 09:35
Hi, 

I am unable to reproduce the issue:

```
○ → docker exec -ti bitnamidockerphabricator_phabricator_1 env
PATH=/opt/bitnami/apache/bin:/opt/bitnami/php/bin:/opt/bitnami/mysql/bin:/opt/bitnami/git/bin:/opt/bitnami/arcanist/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=be011fffe96e
TERM=xterm
PHABRICATOR_HOST=172.17.0.7
```

<img width="1178" alt="screen shot 2017-12-19 at 10 32 33" src="https://user-images.githubusercontent.com/1133777/34150323-52ac0e22-e4a8-11e7-8667-138e1a132e2c.png">


There must be something else we are missing. Can you access when doing `curl 127.0.0.1` in the host where it is running?

**Comment by sameersbn** [comment] 2017-12-28 10:15
> Thanks.
> 
> I change the variable and there is no result:
> 
>     environment:
>       - PHABRICATOR_HOST=178.62.222.122
> 
> inside container:
> 
> $ docker exec -it xxx_phabricator_1 bash
> $ env
> ...
> PHABRICATOR_HOST=178.62.222.122
> ...
> 
> And after that I have the same results:
> 
> Site Not Found
> This request asked for "/" on host "178.62.222.122", but no site is configured which can serve this request.

@pahaz can you try 

```
$ docker-compose down -v && \
   docker-compose up
```

**Comment by sameersbn** [comment] 2017-12-28 10:19
if that does not work, then try the steps mentioned in https://github.com/bitnami/bitnami-docker-ghost/issues/62#issuecomment-354259636

**Comment by dpwolfe** [comment] 2018-08-14 23:44
I ran into this today and the solution from @sameersbn solved it. I put in the elastic IP address that I assigned to the host under the `PHABRICATOR_HOST` var and worked like a charm after pulling it down and putting it back up again. Thanks!

**Comment by javsalgar** [comment] 2018-08-15 08:31
Thanks for letting us know @dpwolfe ! :)

**Closed** 2018-08-15 08:30 UTC
