### ISSUE TITLE
'convert' binary not found or Imagemagick is not installed.

### ISSUE THREAD

**Issue by baldonharris** [bitnami/bitnami-docker-phabricator#165] opened 2021-02-04 04:33 UTC
As title says, I enabled `files.enable-imagemagick` in my Phab setup. Also enabled my imagick extension in my container but the error still persists. Am I missing something?
![image](https://user-images.githubusercontent.com/12781570/106845140-3ce33800-66e5-11eb-9a30-4c586550a03f.png)

**Comment by juan131** [comment] 2021-02-04 10:39
Hi @baldonharris 

What version of the Phabricator container are you using? The Phabricator container doesn't include imagemagick by default. We have guides that explain how to install imagemagick in other images (e.g. Mediawiki: https://github.com/bitnami/bitnami-docker-mediawiki#how-to-install-imagemagick-in-the-bitnami-mediawiki-docker-image). A Dockerfile like the one below should make the trick:


```Dockerfile
FROM bitnami/phabricator:latest

## Change user to perform privileged actions
USER 0
## Install 'imagemagick'
RUN install_packages imagemagick
## Revert to the original non-root user
USER 1001
```

> Also enabled my imagick extension in my container but the error still persists

Could you explain what did you do to do so?

**Comment by baldonharris** [comment] 2021-02-04 12:55
@juan131 Thanks for response!

I can't believe I missed this part in the document! Thank you. I'm using `bitnami/phabricator` image.

> Could you explain what did you do to do so?

I saw this bitnami documentation.
https://docs.bitnami.com/bch/apps/phabricator/configuration/install-modules-php/
![image](https://user-images.githubusercontent.com/12781570/106895444-2eb80a80-672b-11eb-85d5-7e9698075988.png)

**Comment by juan131** [comment] 2021-02-05 07:24
Hi @baldonharris 

Were you able to solve the issue with the workaround I provide you?

> I saw this bitnami documentation.

Please note that documentation is intended for the Bitnami Phabricator Stack (nor the container). That's why you can find instructions that are slightly different.

**Comment by baldonharris** [comment] 2021-02-05 11:37
Hi @juan131 

I'm gonna try this today but I'm pretty sure this will work since it's in the documentation. Thank you so much!

**Comment by juan131** [comment] 2021-02-08 07:38
Great @baldonharris ! Please keep us updated about your progress

**Comment by baldonharris** [comment] 2021-02-12 06:54
@juan131 Hi! Since I already have my phab running, I just logged in to the container and executed
`install_packages imagemagick`

That solved my problem. Thank you! :)

**Comment by javsalgar** [comment] 2021-02-12 11:00
Good to know that the issue is solved. Another option for your use case could be creating a forked container that performs that system installation.

https://github.com/bitnami/bitnami-docker-phabricator#extend-this-image

**Comment by baldonharris** [comment] 2021-02-12 22:24
@javsalgar Hi. Yes, I will definitely do this as this is a much cleaner and proper way. Thanks guys. What a great community! :)

**Comment by juan131** [comment] 2021-02-15 08:12
Great! I proceed to close the issue as "solved". Feel free to reopen it if you require further help.

**Closed by juan131** 2021-02-15 08:12 UTC
