### ISSUE TITLE
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/apache/conf' -> '/opt/bitnami/apache/conf'

### ISSUE THREAD

**Issue by Evaim** [bitnami/bitnami-docker-phabricator#105] opened 2018-08-03 16:20 UTC
hi,
  today i use this image to deploy phabricator,but i get the error:"Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/apache/conf' -> '/opt/bitnami/apache/conf'"

my docker command is :
```
docker run -d --name phabricator -p 9080:80 -p 9443:443 --net phabricator-tier --volume /home/data/phabricator:/bitnami bitnami/phabricator:latest
```
the docker logs:

<img width="1183" alt="default" src="https://user-images.githubusercontent.com/6076639/43653827-d696f9a0-977b-11e8-8c59-537e55987bb0.png">

**Comment by juan131** [comment] 2018-08-06 08:47
Hi @Evaim 

It seems you have data from previous deployments on the local directory  **/home/data/phabricator** which is causing some conflict during the initialisation. Could you share the whole log output?

Are you trying to start Phabricator from scratch? If that's the case and you don't care about the data saved on you local directory. You can simply clean that directory and start again.

**Comment by Evaim** [comment] 2018-08-06 16:48
@juan131 hi,thanks for you help,but this is my first install and the directory "/home/data/phabricator" is empty.
this is the whole operation and logs:
![default](https://user-images.githubusercontent.com/6076639/43729613-727db76c-99db-11e8-8d84-337ad4d9cd42.png)
thanks again:)

**Comment by juan131** [comment] 2018-08-07 07:43
I tried exactly the same command and I was unable to reproduce the issue:

```
$ mkdir /tmp/persistent-directory
$ docker run -d --name phabricator -p 9080:80 -p 9443:43 --volume /tmp/persistent-directory:/bitnami bitnami/phabricator:latest
docker logs phabricator

Welcome to the Bitnami phabricator container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
...
```

Could you please run the command below? I think you have something weird on that directory...

```
ls -la /home/data/phabricator
```

**Comment by Evaim** [comment] 2018-08-07 11:43
I tried exactly the same command of yours, but I got the same error:
```
[root@s153 ~]# mkdir /tmp/persistent-directory
[root@s153 ~]# ls -la /tmp/persistent-directory/
总用量 4
drwxr-xr-x   2 root root    6 8月   7 19:08 .
drwxrwxrwt. 17 root root 4096 8月   7 19:08 ..
[root@s153 ~]# docker run -d --name phabricator -p 9080:80 -p 9443:43 --volume /tmp/persistent-directory:/bitnami bitnami/phabricator:latest
ce075813e8a68e5df6049565ec9ee23f4a64a82a1c773e1886c7df32db969449
[root@s153 ~]# docker logs phabricator

Welcome to the Bitnami phabricator container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/apache/conf' -> '/opt/bitnami/apache/conf'
[root@s153 ~]# ls -la /tmp/persistent-directory/
总用量 4
drwxr-xr-x   3 root root   19 8月   7 19:08 .
drwxrwxrwt. 17 root root 4096 8月   7 19:08 ..
drwxr-xr-x   3 root root   17 8月   7 19:08 apache
```
the screen capture:
![default](https://user-images.githubusercontent.com/6076639/43772760-c33865f4-9a75-11e8-9812-2e3421088f7f.png)

**Comment by juan131** [comment] 2018-08-07 11:57
Just to ensure we're using exactly the same image. Could you start from scratch and run the command below?

```
docker run -d --name phabricator -p 9080:80 -p 9443:43 --volume /tmp/persistent-directory:/bitnami bitnami/phabricator:2018.30.0-debian-9-r6 
```

It will ensure you use the latest version (**2018.30.0-debian-9-r6** )

**Comment by Evaim** [comment] 2018-08-07 12:36
it has the same error:(

```
[root@s153 tmp]# mkdir /tmp/persistent-directory
[root@s153 tmp]# ls -la /tmp/persistent-directory/
总用量 4
drwxr-xr-x   2 root root    6 8月   7 20:34 .
drwxrwxrwt. 17 root root 4096 8月   7 20:34 ..
[root@s153 tmp]# docker run -d --name phabricator -p 9080:80 -p 9443:43 --volume /tmp/persistent-directory:/bitnami bitnami/phabricator:2018.30.0-debian-9-r6
555b360bf4fc0146429f1abda05f292518de222d19f29c7f81b28ea4b3e3527d
[root@s153 tmp]# docker logs 555b360bf4fc014

Welcome to the Bitnami phabricator container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/apache/conf' -> '/opt/bitnami/apache/conf'
```

![default](https://user-images.githubusercontent.com/6076639/43776118-765ae264-9a81-11e8-92f0-4735a8221cde.png)

**Comment by juan131** [comment] 2018-08-08 07:29
Hi @Evaim 

It's very weird.. Let's try to add more verbosity on the logs. Could you try running the commands below?

```
docker stop phabricator && docker rm phabricator
docker run -d --name phabricator -p 9080:80 -p 9443:43 --volume /tmp/persistent-directory:/bitnami   --env NAMI_DEBUG='--log-level=trace'  bitnami/phabricator:2018.30.0-debian-9-r6 
```

**Comment by Evaim** [comment] 2018-08-08 10:01
hi @juan131 
the output:
```
[root@s153 tmp]# docker run -d --name phabricator -p 9080:80 -p 9443:43 --volume /tmp/persistent-directory:/bitnami   --env NAMI_DEBUG='--log-level=trace'  bitnami/phabricator:2018.30.0-debian-9-r6
070f64e35516c363b18dc795d6709d481b51aadd7cebf577b1345ab1e9490c6e
[root@s153 tmp]# docker logs 070f64e35516
app-entrypoint.sh 09:58:57.29
app-entrypoint.sh 09:58:57.29 Welcome to the Bitnami phabricator container
app-entrypoint.sh 09:58:57.29 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
app-entrypoint.sh 09:58:57.30 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues
app-entrypoint.sh 09:58:57.30
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
apache  TRACE [prepareDataToPersist] Preparing /opt/bitnami/apache/conf to persist in /bitnami/apache/conf
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/apache/conf' -> '/opt/bitnami/apache/conf'
nami    TRACE Error: Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/apache/conf' -> '/opt/bitnami/apache/conf'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1048:18)
    at Object.link (/opt/bitnami/nami/node_modules/nami-utils/lib/file/link.js:34:8)
    at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:285)
    at _.each (/root/.nami/components/com.bitnami.apache/lib/volume.js:132:13)
    at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
    at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
    at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:285)
    at Object.prepareDataToPersist (/root/.nami/components/com.bitnami.apache/lib/volume.js:121:7)
    at Service.$app.postInstallation (/root/.nami/components/com.bitnami.apache/main.js:35:21)
```
![default](https://user-images.githubusercontent.com/6076639/43830868-e7be0482-9b34-11e8-831a-96ab9c19d9de.png)

**Comment by juan131** [comment] 2018-08-09 11:26
Hi @Evaim 

Are you able to reproduce the same error on a different environment? Other OS, a VM, another computer? I also noticed you're running docker as root 'user', it should not affect anyway...

I've tried to reproduce the error on MacOS, Ubuntu, DinD... And I'm unable to reproduce it...

**Comment by Evaim** [comment] 2018-08-14 17:33
Hi @juan131 
Today, I have upgrade the docker version, from 13.xx to 17.03, it runs sucessfully, maybe the docker version 13.xx was not compatible to the image.

Thanks a lot~

**Comment by juan131** [comment] 2018-08-15 07:39
Hi @Evaim 

Great!! I'm glad you could finally fix the issue by updating your Docker version!! There could be some issues with permissions on that Docker version or sth similar. 

I proceed to close this issue, please feel free to reopen it if you face similar issues.

**Closed by juan131** 2018-08-15 07:39 UTC
