### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ahmed20391849** [bitnami/bitnami-docker-phabricator#145] opened 2020-04-24 14:20 UTC
![image](https://user-images.githubusercontent.com/34915846/80222671-1a44ce80-863f-11ea-8828-e3b4e69a4419.png)

**Comment by juan131** [comment] 2020-04-27 07:28
Hi @ahmed20391849 

I'm closing this ticket as a duplicate of https://github.com/bitnami/bitnami-docker-phabricator/issues/145

**Closed by juan131** 2020-04-27 07:28 UTC
